### PR TITLE
Change driver version data type

### LINKED ISSUE #8: Wrong return type for `driver_version`
The [`driver_version`](https://docs.rs/voodoo/0.3.1/voodoo/struct.PhysicalDeviceProperties.html#method.driver_version) function returns a [`voodoo::Version`](https://docs.rs/voodoo/0.3.1/voodoo/struct.Version.html) structure.

However, the spec does not say if this is in the same format as a Vulkan version. It's just a `u32`, its format is driver-specific.

### PR DESCRIPTION
**Pull request by GabrielMajeri**
Fixes #8

### CODE REVIEW

**Comment by c0gent** [comment]
Looks great :)

I'm not at home so I'll have a closer look tomorrow or Sunday before I merge.

Thanks!

**Comment by c0gent** [comment]
I don't have Windows working right now and Vulkan doesn't work on my gpus (AMD 280x) in linux. Have you tested these changes and does the example run, etc.? If so I will just merge.

**Comment by c0gent** [comment]
Also, how would you like to be a maintainer of this repository? :)

**Comment by GabrielMajeri** [comment]
> Have you tested these changes and does the example run, etc.?

Yes, I've run the examples and they still work. Although this is a breaking change for other users of the Voodoo crate, assuming they used the returned driver version somehow. We should try setting up Travis CI sometime (even if we can't _run_ the code, we can check if it still _builds_ at least).

> Also, how would you like to be a maintainer of this repository? :)

I think it's too early to decide :)
I will keep contributing to this crate when I can, but I don't think I'm familiar enough with either Vulkan or the code in this crate to become an official maintainer.

**Comment by c0gent** [comment]
Ok great. I'm happy to help you make any changes you want to make I just have no time right now to properly maintain this repo. I'll leave this open as a reminder to myself to make a note of the breakage in the changelog.

Thanks again and let me know if you change your mind about maintaining. Don't worry, if you make any mistakes they can always be fixed!

**Comment by c0gent** [comment]
Sorry to take so long. This is merged :)

**Pull request closed without merging**
